mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^questionnaires/', include('questionnaires.urls')),
]

questionnaires/urls.py
from django.conf.urls import url
from . import views

app_name = 'questionnaires'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^login/', views.UserLoginView.as_view(), name='login'),
    url(r'^logout/', views.logout_view, name='logout'),
    url(r'^register/', views.UserRegistrationView.as_view(), name='register'),
    url(r'^create-questionnaire/', views.QuestionnaireCreate.as_view(), name='create-quest')
]

questionnaires/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse


class Questionnaire(models.Model):
    name = models.CharField(max_length=250)
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def get_absolute_url(self):
        return reverse('questionnaires:index')

    def __str__(self):
        return self.name


class Outcome(models.Model):
    questionnaire = models.ForeignKey(Questionnaire, on_delete=models.CASCADE)
    name = models.CharField(max_length=250)


class Page(models.Model):
    questionnaire = models.ForeignKey(Questionnaire, on_delete=models.CASCADE)


class Question(models.Model):
    text = models.TextField()
    page = models.ForeignKey(Page, on_delete=models.CASCADE)


class Answear(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    score = models.IntegerField()


class Result(models.Model):
    text = models.TextField()

questionnaires/forms.py
from django.contrib.auth.models import User
from django import forms
from questionnaires.models import *


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

questionnaires/views.py
from .models import Questionnaire
from django.views.generic import ListView, View, CreateView
from django.contrib.auth.views import LoginView
from django.contrib.auth import logout
from .forms import UserForm
from django.shortcuts import redirect, render


class IndexView(ListView):
    template_name = 'questionnaires/index.html'
    context_object_name = 'all_questionnaires'

    def get_queryset(self):
        return Questionnaire.objects.all()


class UserLoginView(LoginView):
    template_name = 'questionnaires/generic_template_form.html'
    redirect_field_name = 'questionnaires:index'


def logout_view(request):
    logout(request)
    return redirect('questionnaires:index')


class UserRegistrationView(View):
    form_class = UserForm
    template_name = 'questionnaires/generic_template_form.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()
            return redirect('questionnaires:index')

        return render(request, self.template_name, {'form': form})


class QuestionnaireCreate(CreateView):
    model = Questionnaire
    fields = ['name', 'description']
    template_name = 'questionnaires/generic_template_form.html'

    def form_valid(self, form):
        questionnaire = form.save(commit=False)
        questionnaire.user = self.request.user
        return super(QuestionnaireCreate, self).form_valid(form)

questionnaires/templates/questionnaires/form-template.html
{% if form.errors %}
    {% for error in form.non_field_errors %}
        <strong>{{ error|escape }}</strong>
    {% endfor %}
{% endif %}

{% for field in form %}
    {{ field.errors }}
    <label>{{ field.label_tag }}</label>
    {{ field }}
{% endfor %}

questionnaires/templates/questionnaires/generic_template_form.html
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {% include 'questionnaires/form-template.html' %}
    <button type="submit">Submit</button>
</form>

questionnaires/templates/questionnaires/index.html
<ul>
    {% for questionnaire in all_questionnaires %}
        <li><a href="#">{{ questionnaire }}</a></li>
    {% endfor %}
</ul>
{% if user.is_authenticated %}
    <h2><strong>{{ user }}</strong></h2>
    <a href="{% url 'questionnaires:create-quest' %}">Create Questionnaire</a><br>
    <a href="{% url 'questionnaires:logout' %}">Logout</a><br>
{% else %}
<a href="{% url 'questionnaires:login' %}">Login</a><br>
<a href="{% url 'questionnaires:register' %}">Register</a>
{% endif %}